name: build
on: [push]

jobs:
  build:
    name: build application
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v7

    - name: Build application
      run: dotnet build Chemo.slnx -c Release -warnaserror

    - name: Run tests
      run: dotnet test Chemo.slnx -c Release --no-build

    - name: Check formatting
      run: dotnet format Chemo.slnx --verify-no-changes --no-restore
